import type React from "react"
import type { Metadata } from "next"

import "./globals.css"
import { Figtree, Inter, Geist_Mono, Anton as V0_Font_Anton, Space_Grotesk } from "next/font/google"

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  weight: ["300", "400", "500", "600", "700", "800"],
})

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const anton = V0_Font_Anton({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-anton",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  weight: ["400", "500", "600"],
})

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Setu",
  description: "Generated by v0",
  icons: {
    icon: "/icon.svg",
  },
    generator: 'v0.app'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${figtree.variable} ${geistMono.variable} ${anton.variable} ${space.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
